# Set Up

In [1]:
import requests
from io import StringIO
import pandas as pd
import numpy as np

In [2]:
from platform import python_version
print(python_version())

3.9.7


In [3]:
import sys
!{sys.executable} -m pip install sentence-transformers

In [4]:
import os
os .chdir('C:\\Users\\Kristin\\Documents\\DataSets')

In [5]:
DOCS = pd.read_csv('pm-abstracts-DOCS2-CT.csv')
DOCS

abstract_id                                            doc_str
0         11744656   During exercise, pulse oximetry is problemati...
1         11744658   The physiological and metabolic demands of hi...
2         11744678   This study compared the effect of repetitive ...
3         11774067   Abstract. Relations between frequently used i...
4         11782651   PURPOSE: To investigate the influences of men...
...            ...                                                ...
20306     36235628   This research examined the effects of single-...
20307     36237580   The issue of sports injury and rehabilitation...
20308     36243785   Women with overweight or obesity (OWOB) have ...
20309     36246968   PURPOSE: Cervical radiculopathy is disorder o...
20310     36249264   OBJECTIVE: Cognitive function is essential in...

[20311 rows x 2 columns]

In [22]:
#DOCS = DOCS[0:1000]

In [23]:
#DOCS

In [24]:
sentences = DOCS['doc_str'].tolist()
len(set(sentences))

20311

In [25]:
from sentence_transformers import SentenceTransformer
# initialize sentence transformer model
model = SentenceTransformer('bert-base-nli-mean-tokens')

In [1]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

Downloading:   0%|          | 0.00/1.18k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/612 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/116 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/39.3k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/350 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/13.2k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/349 [00:00<?, ?B/s]

In [2]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("sentence-transformers/multi-qa-mpnet-base-dot-v1")

Downloading:   0%|          | 0.00/737 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/8.65k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/571 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/116 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/25.5k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/438M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/239 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/363 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/13.9k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/229 [00:00<?, ?B/s]

In [3]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("sentence-transformers/all-mpnet-base-v2")

Downloading:   0%|          | 0.00/1.18k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/571 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/116 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/39.3k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/438M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/239 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/363 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/13.1k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/349 [00:00<?, ?B/s]

In [26]:
data = []
k = 1000
for i in (range(0, len(DOCS), k)):
    df = DOCS.iloc[i:i+k]
    print(i, df.iloc[0].name, df.iloc[-1].name)
    data.append(model.encode(df['doc_str'].tolist()))

0 0 999
1000 1000 1999
2000 2000 2999
3000 3000 3999
4000 4000 4999
5000 5000 5999
6000 6000 6999
7000 7000 7999
8000 8000 8999
9000 9000 9999
10000 10000 10999
11000 11000 11999
12000 12000 12999
13000 13000 13999
14000 14000 14999
15000 15000 15999
16000 16000 16999
17000 17000 17999
18000 18000 18999
19000 19000 19999
20000 20000 20310


In [37]:
e = np.concatenate(data, axis=0 )
e.shape

(20311, 768)

In [72]:
from numpy import savetxt
savetxt('embed.csv', e, delimiter=',')

In [74]:
from numpy import loadtxt
e = loadtxt('embed.csv', delimiter=',')
type(e)

numpy.ndarray

In [38]:
#from sentence_transformers import SentenceTransformer
# #initialize sentence transformer model
#model = SentenceTransformer('bert-base-nli-mean-tokens')
# #create sentence embeddings
#sentence_embeddings = model.encode(sentences)
#sentence_embeddings.shape

In [39]:
#sentence_embeddings

# IndexFlatL2

In [6]:
import faiss

In [41]:
d = e.shape[1]
d

768

In [42]:
index = faiss.IndexFlatL2(d)

In [43]:
index.is_trained

True

In [45]:
index.add(e)

In [46]:
index.ntotal

20311

In [47]:
k = 4
xq = model.encode(["Someone sprints with a football"])

In [48]:
%%time
D, I = index.search(xq, k)  # search
print(I)

[[ 7022 13099  7032 12500]]
Wall time: 21.4 ms


In [50]:
DOCS['doc_str'].iloc[[7022, 13099, 7032, 12500]]

7022      The aims of this study were to investigate th...
13099     Keen, ML, Miller, KC, and Zuhl, MN. Thermoreg...
7032      The purpose of this study was to examine the ...
12500     Jacobson, BH, Monaghan, TP, Sellers, JH, Conc...
Name: doc_str, dtype: object

In [51]:
# we have 4 vectors to return (k) - so we initialize a zero array to hold them
vecs = np.zeros((k, d))
# then iterate through each ID from I and add the reconstructed vector to our zero-array
for i, val in enumerate(I[0].tolist()):
    vecs[i, :] = index.reconstruct(val)

In [52]:
vecs.shape

(4, 768)

In [53]:
vecs[0][:100]

array([-0.97436404,  0.14783341, -0.31010962,  0.26976976, -0.05099799,
       -0.31195298,  0.09527801, -0.68362606,  0.13291198, -0.34858063,
        0.39745465,  1.10811222,  0.34787804, -0.44078147,  0.2139215 ,
        0.39450628, -0.32138923, -0.66402072,  0.00865781,  0.03148104,
       -0.68456042, -0.22041503,  0.16854294,  0.54000419,  0.99322772,
        1.13564062, -0.16773945,  0.62119645, -1.29021156,  0.26743504,
        0.18216205,  0.80891174, -0.45164675, -0.25736222, -0.87579972,
        0.34013271,  0.61855704, -0.53742403, -0.04576756, -0.2695367 ,
       -0.34572101,  0.03571805, -0.95085889, -0.73235458, -1.38435411,
       -0.00198412, -0.44313613,  0.04312319, -0.33773652, -0.5442543 ,
        0.10220414,  0.91793346, -0.95042217, -0.24471465, -0.3120364 ,
        0.4288235 ,  0.27578112, -0.53933299, -0.39352304, -1.16048527,
       -0.6997357 ,  0.63283616, -0.34364736,  0.24428934, -0.46596292,
        0.13643257,  0.57823956, -0.44154525, -0.81968367, -0.01

# Partitioning the Index

In [54]:
nlist = 50  # how many cells to create
quantizer = faiss.IndexFlatL2(d)
index = faiss.IndexIVFFlat(quantizer, d, nlist)

In [55]:
index.is_trained

False

In [57]:
index.train(e)
index.is_trained  # check if index is now trained

True

In [58]:
index.add(e)
index.ntotal  # number of embeddings indexed

20311

In [59]:
%%time
D, I = index.search(xq, k)  # search only one cell
print(I)

[[12500 13047  9868  4663]]
Wall time: 5.21 ms


In [60]:
index.nprobe = 10 # set how many of nearest cells to search, better accuracy

In [61]:
%%time
D, I = index.search(xq, k)  # search
print(I)

[[ 7022 13099  7032 12500]]
Wall time: 3.68 ms


In [62]:
index.make_direct_map()

In [63]:
index.reconstruct(7022)[:100]

array([-0.97436404,  0.1478334 , -0.31010962,  0.26976976, -0.05099799,
       -0.31195298,  0.09527801, -0.68362606,  0.13291198, -0.34858063,
        0.39745465,  1.1081122 ,  0.34787804, -0.44078147,  0.2139215 ,
        0.39450628, -0.32138923, -0.6640207 ,  0.00865781,  0.03148104,
       -0.6845604 , -0.22041503,  0.16854294,  0.5400042 ,  0.9932277 ,
        1.1356406 , -0.16773945,  0.62119645, -1.2902116 ,  0.26743504,
        0.18216205,  0.80891174, -0.45164675, -0.25736222, -0.8757997 ,
        0.3401327 ,  0.61855704, -0.537424  , -0.04576756, -0.2695367 ,
       -0.345721  ,  0.03571805, -0.9508589 , -0.7323546 , -1.3843541 ,
       -0.00198412, -0.44313613,  0.04312319, -0.33773652, -0.5442543 ,
        0.10220414,  0.91793346, -0.95042217, -0.24471465, -0.3120364 ,
        0.4288235 ,  0.27578112, -0.539333  , -0.39352304, -1.1604853 ,
       -0.6997357 ,  0.63283616, -0.34364736,  0.24428934, -0.46596292,
        0.13643257,  0.57823956, -0.44154525, -0.8196837 , -0.01

# IndexIVFPQ index

In [64]:
m = 8  # number of centroid IDs in final compressed vectors
bits = 8 # number of bits in each centroid

quantizer = faiss.IndexFlatL2(d)  # we keep the same L2 distance flat index
index = faiss.IndexIVFPQ(quantizer, d, nlist, m, bits) 

In [65]:
index.is_trained

False

In [66]:
index.train(e)

In [67]:
index.add(e)

In [68]:
index.nprobe = 10  # align to previous IndexIVFFlat nprobe value

In [69]:
%%time
D, I = index.search(xq, k)
print(I)

[[13099  3869  7022 19948]]
Wall time: 5 ms


In [70]:
[f'{i}: {sentences[i]}' for i in I[0]]

['13099:  Keen, ML, Miller, KC, and Zuhl, MN. Thermoregulatory and perceptual effects of apercooling garment worn underneath an American football uniform. J Strength Cond Res 31(11): 2983-2991, 2017-American football athletes are at the highest risk of developing exertional heat illness (EHI). We investigated whether percooling (i.e., cooling during exercise) garments affected perceptual or physiological variables in individuals exercising in the heat while wearing football uniforms. Twelve male participants (age = 24 ± 4 year, mass = 80.1 ± 8.5 kg, height = 182.5 ± 10.4 cm) completed this cross-over, counterbalanced study. On day 1, we measured peak oxygen consumption (V[Combining Dot Above]O2). On days 2 and 3, participants wore percooling garments with (ICE) or without (CON) ice packs over the femoral and brachial arteries. They donned a football uniform and completed 3, 20-minute bouts of treadmill exercise at ∼50% of peak V[Combining Dot Above]O2 (∼33° C, ∼42% relative humidity) f